### PR TITLE
Relax redis version

### PR DESCRIPTION
**Pull request by lorismaz**
This PR allows newer versions of redis

### CODE REVIEW

**Comment by jeopard** [comment]
hi @lorismaz ! Sorry for the delay on this, last week was pretty hectic. I'm not sure I understand the change. What's the redis gem version you want to have?

**Comment by jeopard** [comment]
@lorismaz ping! :)

**Comment by lorismaz** [comment]
Hey @jeopard thanks for the message, I actually needed any version that is in 4, I was using 4.2.5. 
For your gem to work I had to update this and also change the way the requirements were loaded using Dir instead of FileList, I can send a PR for this too if it make sense to the project.

**Comment by jeopard** [comment]
thanks @lorismaz , I'll merge this now!

As for `FileList`, how does it fail? Please send a PR if it's not too much trouble :)

**Comment by jeopard** [comment]
the new gem version 0.1.4 was published :)

**Pull request merged**
